<?php
/**
 * Navigate Commerce
 *
 * @author        Navigate Commerce
 * @package       Navigate_HomepageBannerSlider
 * @copyright     Copyright (c) Navigate (https://www.navigatecommerce.com/)
 * @license       https://www.navigatecommerce.com/end-user-license-agreement
 */

$slidercount = 0;
$isEnableSlider = "";
$collection  = $block->getSliderCollection();
$slidercount = $collection->count();
$mediaUrl    = $block->getMediaUrl();
$sliderLoop  = $block->getSliderLoop();
$sliderDots  = $block->getSliderDots();
$sliderArrow = $block->getSliderArrow();
$sliderAutoplay = $block->getSliderAutoplay();
$sliderDesktopItem = $block->getDesktopItemCount();
$sliderMobileItem  = $block->getMobileItemCount();
$sliderAutoPlaySpeed = $block->getSliderAutoplayTiming();
if ($slidercount > 1) { $isEnableSlider = "owl-carousel owl-theme"; }

if ($slidercount > 0) { ?>
<div class="main-home-slider_section">
    <div class="main-home-slider <?= /* @noEscape */ $isEnableSlider ?>">
        <?php foreach ($collection as $slider) { ?>
            <?php if ($slider->getEnableButton() == 1 && !empty($slider->getTextPosition())) {
                    $textPosition = $slider->getTextPosition();
            } else {
                $textPosition = 'center';
            } ?>
            <div class="main-home-slider-img desktop-section-bannerslider <?= /* @noEscape */ $textPosition;?>"
            href="<?= /* @noEscape */ ($slider->getUrlKey()) ? $slider->getUrlKey() : "javascript:void(0)" ?>" <?php if (!empty($slider->getUrlKey())) { ?> target="_blank" <?php } ?>> <?php // phpcs:ignore ?>
                <img src="<?php echo $block->escapeHtml($mediaUrl.$slider->getImagename()); ?>" alt="<?= $slider->getTitle() ?>" title="<?= $slider->getTitle() ?>"> <?php // phpcs:ignore ?>
                <?php if (!empty($slider->getSlidertitle()) || $slider->getEnableButton() == 1) { ?>
                    <div class="main-home-slider-info" >
                        <div class="main-home-slider-info-inner">
                            <?php if ($slider->getSlidertitle()) { ?>
                                <h3 class="main-home-slider-info-title"><?= $slider->getSlidertitle() ?></h3> <?php // phpcs:ignore ?>
                            <?php } ?>
                            <?php if ($slider->getEnableButton() == 1) { ?>
                                <a href="<?= /* @noEscape */ ($slider->getUrlKey()) ? $slider->getUrlKey() : "javascript:void(0)" ?>" <?= /* @noEscape */ ($slider->getOpenNewTab() == 1) ? 'target="_blank"' : "" ?> class="main-home-slider-info-button action" title="<?= /* @noEscape */ $block->escapeHtml($slider->getButtontitle()) ?>"> <?php // phpcs:ignore ?>
                                    <?= /* @noEscape */ $block->escapeHtml($slider->getButtontitle()) ?>
                                </a>
                            <?php } ?>
                        </div> 
                    </div>
                <?php } ?>
            </div>
            <div class="main-home-slider-img mobile-section-bannerslider <?= /* @noEscape */ $textPosition;?>"
            href="<?= /* @noEscape */ ($slider->getUrlKey()) ? $slider->getUrlKey() : "javascript:void(0)" ?>" <?php if (!empty($slider->getUrlKey())) { ?> target="_blank" <?php } ?>> <?php // phpcs:ignore ?>
                <?php
                    $imageUrl = $imageUrlLink = '';
                if (!empty($slider->getMobileimagename())) {
                    $imageUrl = $slider->getMobileimagename();
                } else {
                    $imageUrl = $slider->getImagename();
                }
                    $imageUrlLink = $block->escapeHtml($mediaUrl.$imageUrl);
                ?>
                <img src="<?= $imageUrlLink; ?>" alt="<?= $slider->getTitle() ?>" title="<?= $slider->getTitle() ?>"> <?php // phpcs:ignore ?>
                <?php if (!empty($slider->getSlidertitle()) || $slider->getEnableButton() == 1) { ?>
                    <div class="main-home-slider-info" >
                        <div class="main-home-slider-info-inner">
                            <?php if (!empty($slider->getSlidertitle()) || !empty($slider->getMobilesliderTitle())) { ?>
                                <?php if (!empty($slider->getMobilesliderTitle())) {
                                    $sliderTitle = $slider->getMobilesliderTitle();
                                } else {
                                    $sliderTitle = $slider->getSlidertitle();
                                } ?>
                                <h3 class="main-home-slider-info-title"><?= /* @noEscape */ $sliderTitle ?></h3>
                            <?php } ?>
                            <?php if ($slider->getEnableButton() == 1) { ?>
                                <a href="<?= /* @noEscape */ ($slider->getUrlKey()) ? $slider->getUrlKey() : "javascript:void(0)" ?>" <?= /* @noEscape */ ($slider->getOpenNewTab() == 1) ? 'target="_blank"' : "" ?> class="main-home-slider-info-button action" title="<?= /* @noEscape */ $block->escapeHtml($slider->getButtontitle()) ?>"> <?php // phpcs:ignore ?>
                                    <?= /* @noEscape */ $block->escapeHtml($slider->getButtontitle()) ?>
                                </a>
                            <?php } ?>
                        </div> 
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
</div>
<?php } ?>
<?php
    $bannerSliderConfig = [];
    $bannerSliderConfig['bannerSlider_infinite']    = $sliderLoop;
    $bannerSliderConfig['bannerSlider_showDots']    = $sliderDots;
    $bannerSliderConfig['bannerSlider_autoplay']    = $sliderAutoplay;
    $bannerSliderConfig['bannerSlider_showArrow']   = $sliderArrow;
    $bannerSliderConfig['bannerSlider_itemMobile']  = $sliderMobileItem;
    $bannerSliderConfig['bannerSlider_itemDesktop'] = $sliderDesktopItem;
    $bannerSliderConfig['bannerSlider_items']       = $slidercount;
    $bannerSliderConfig['bannerSlider_autoplayTimeout'] = $sliderAutoPlaySpeed;
?>
<script>
    window.bannerSliderData = <?= /* @noEscape */ json_encode($bannerSliderConfig); ?>;
</script>